"""empty message

Revision ID: 202de54efae5
Revises: d93d356524ee
Create Date: 2019-08-09 00:09:38.729627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '202de54efae5'
down_revision = 'd93d356524ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('color', sa.String(length=9), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'color')
    # ### end Alembic commands ###
