"""empty message

Revision ID: 38507c8db286
Revises: 123aa9e4e962
Create Date: 2020-02-03 19:52:16.124078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38507c8db286'
down_revision = '123aa9e4e962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('color', sa.String(length=6), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'color')
    # ### end Alembic commands ###
