"""empty message

Revision ID: 4fba71512565
Revises: 645546f4de86
Create Date: 2020-02-03 20:30:02.902021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fba71512565'
down_revision = '645546f4de86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('color', sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'color')
    # ### end Alembic commands ###
