"""empty message

Revision ID: 645546f4de86
Revises: 38507c8db286
Create Date: 2020-02-03 20:29:44.198497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '645546f4de86'
down_revision = '38507c8db286'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'color')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('color', sa.VARCHAR(length=6), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
