"""empty message

Revision ID: 94245c4b11b3
Revises: 202de54efae5
Create Date: 2019-12-15 20:36:08.553078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94245c4b11b3'
down_revision = '202de54efae5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tag', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('user', 'password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('user', 'password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.drop_column('user', 'is_active')
    op.alter_column('tag', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
