"""empty message

Revision ID: d93d356524ee
Revises: 032c67b8d5cc
Create Date: 2019-08-08 22:39:06.413355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd93d356524ee'
down_revision = '032c67b8d5cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('tag', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_tag_timestamp'), 'tag', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tag_timestamp'), table_name='tag')
    op.drop_column('tag', 'timestamp')
    op.drop_column('tag', 'is_active')
    # ### end Alembic commands ###
